baseURL = "https://li3t.com/"
title = "li3t"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "ak"
  description = "Sometimes you are the snake and sometimes you are the hoe."
  github = "ajkoop"
  instagram = "ajkoop"
  email = "aj@li3t.com"
  url = "https://koop.ws"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "United States"
  userStatusEmoji = "😀"
  enableGitalk = true
  enableSearch = true

  [[params.links]]
    title = "Link"
    href = "https://github.com/ajkoop"
  [[params.links]]
    title = "Link2"
    href = "https://koop.ws"
    icon = "https://li3t/images/me.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

